Settings:
  ForceUpdateInventories: false
Messages:
  Prefix: '&7[&6AdvancedCustomMenu&7]'
  NoPermission: '%prefix% &cSorry! &fYou do not have permission for this command!'
  Reload: '%prefix% &aConfig and Messages Reloaded!'
  NotExist: '%prefix% &cThe menu &e%menu%&c does not exist!'
  Invalid: '%prefix% &cWhoops! &7Invalid argument, try &e/%command% help&7!'
  Price: '%prefix% &cSorry! &7You must have atleast &f$%price% &7to us this!' # Added in 1.2.1
